FROM node:13.12.0-alpine as base

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install --global http-server

COPY . ./

RUN apk --no-cache add curl
RUN apk add --no-cache bash

CMD ["/app/run"]


